"use strict";
let estaChovendo = false;
estaChovendo = true;
let idade = 27;
let altura = 1.75;
let nacionalidade = 'brasileiro';
const sobrenome = ['paulo', 'Fernando', 'Matheus'];
const colegas = ['Marcão', 'Marcia', 'Felipe'];
const notas = [7, 9, 5, 8];
const lista = ['Vinicius', true, 25];
let anoNascimento = 2024;
anoNascimento = 'dois mil e viinte e quatro';
